config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories do
    resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def new    
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:title)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @category = Category.find(params[:category_id])
    @post = Post.new
  end

  def edit
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.create(post_params)
    
    redirect_to category_path(@category)
  end

  def update
    @category = Category.find(params[:category_id])
    @post = @category.posts.find(params[:id])
    @post.update(post_params)
    redirect_to category_path(@category)
  end

  def destroy
  end

  private
    def post_params
      params.require(:post).permit(:username, :title, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved: 
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category:</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>Select your Category</h2>
<h3>Or create a <%= link_to 'New Category', new_category_path %> </h3>

<table>
  <tr>
    <th>Title:</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.title %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category:</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h3>
  <strong>Category:</strong>
  <%= @category.title %>
</h3>

<h4>Create a <%= link_to 'new Post', new_category_post_path(@category) %></h4>

<% @posts.each do |post| %>
  <p><%= post.username %> posted <%= post.title %></p>
<% end %>

<%= link_to 'Edit', edit_category_path %> | 
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craigslist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Craig'sList Jr. (Rails Edition)</h1>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for([@category, @category.posts.create]) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited this category from being saved: %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', categories_path %>